# Project information

site_name: 'Learn Continuous Deployment With Static Site Generators'
site_description: 'In this course we will learn how to deploy websites in continuous deployment with static site generators. We will try to understand numerous Web Dev and hosting concepts and to practice them.'
site_author: 'François-Emmanuel Goffinet'
site_url: 'https://learn-cd-staticgen.goffinet.org/'
google_analytics:
  - 'UA-21733018-12'
  - 'auto'
copyright: 'Copyright &copy; 2017 François-Emmanuel Goffinet'
repo_name: 'goffinet/learn-cd-staticgen'
repo_url: 'https://github.com/goffinet/learn-cd-staticgen/'

# Theme

theme_dir: 'material/'
theme: 'material'

# Options

extra:
  language: en
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'purple'
  disqus: 'www-goffinet-org'
  logo:
    icon: 'school'
  social:
    - type: 'github'
      link: 'https://github.com/goffinet'
    - type: 'twitter'
      link: 'https://twitter.com/fegoffinet'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/fegoffinet/'
    - type: 'building-o'
      link : 'https://www.goffinet.org'
    - type: 'book'
      link : 'https://biblio.goffinet.org'

# Extensions

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Content structure

pages:
- 'Course Presentation': 'index.md'
- 'In English':
  - '1. First continuous deployment project': 'first-continous-deployment-project.md'
  - '2. Other Projects with static site generators': 'other-projects-with-static-site-generators.md'
  - '3. Learn Markdown': 'markdown-styling.md'
- 'En français':
  - 'Premier projet en déploiement continu': 'noway.md'
  - 'Autre projets avec générateur de site statique': 'noway.md'
